- Array/Largest_element(krishita30j).py
Added Largest element of an array solution under Array section.
> Added Largest element of an array (python)

- Array/devmohit-live_gcd.py
Added program to compute the Greatest Common Divisor of two given numbers using Python3. 🚀
> GCD of Two number in Python | Mohit 

- Binary Tree/basscoder2808_height_of_a_binary_tree.c
- Binary Tree/basscoder2808_inorder_tree_traversal.c
I have added the program for finding the height of the binary tree in the required folder.
> Height of the Binary Tree #26

- String/SparshGarg_CheckPalindrome.java
> SparshGarg_CheckPalindrome.java

- Binary Search Tree/Sumanth_Postorder_Traversal.py
Recursive postorder traversal of Binary Search Tree in Python 😃
> Postorder Traversal 

- SegmentTree/Segmenttreermq.java
- Stack/INFIX12.C
This is the code in C for conversion from infix to postfix expression.For Hacktoberfest 2020
> added infix to postfix conversion code using stack

- Binary Tree/rasacharjee_heightOfBinaryTree.cpp
I have attached a pr which solves the problem of finding the height of binary tree. I will be grateful if my pr is merged!
> Added rasacharjee_heightOfBinaryTree.cpp file

- Linked List/sourabhkumar45_search_list.cpp
Ask user to enter elements in linked list and then ask user to search a particular element in the list.
Merging will be motivating for me as it is my first PR.
> Added search list for element

- Queue/Sunil_Queue_linked_list.c
Implementation of the queue using a linked list
> Queue using linked list

- Linked List/UtkarshGoel22_reverse_Linked_List.cpp
I have added the code for reversing the linked list in c++14.
> Add reverse linked code in c++14

- Binary Tree/sgavil_lowest-common-ancestor.cpp
C++ implementation with O(n) complexity
> Added C++ implementation for Lowest Common Ancestor for Binary Tree

- Array/pranav108_bubble_sort.c
- Matrix/pranav108_involutary_matrix.c
- Queue/pranav108_queue_using_stack.c
- Stack/pranav108_STACK.c
> Basic Stack code

- Binary Tree/sukritishah15_inorderTraversal.cpp
Adding C++ code for Inorder Tree Traversal (Issue #19)
Let me know if any changes are to be made.
Thank you! @G1Joshi
> Adding C++ code for Inorder Tree Traversal (Issue #19)

- Binary Tree/charul090_maximum_in_binary_tree.py
Added maximum in binary tree implementation in python
> Maximum in binary tree implementation in python

- Array/Sumeetweb_RemoveDuplicateElements.java
Program to remove duplicate elements in Array using Java
> Remove Duplicate Elements in Array

- Linked List/rahul_linkedList_Pallindrome.java
> Pallindrome LinkedList

- Queue/sb2356-iiitr_circular-q-using-ll.c
Added an implementation of a circular queue using a linked list in C.
> Added Circular Queue

- Array/Kadane's Algorithm.cpp
This algorithm helps us in finding the subarray with maximum sum
> Added Kadane's Algorithm

- Binary Tree/sukritishah15_preorderTraversal.cpp
Adding C++ Code for Preorder Tree Traversal (Issue #20)
Please let me know if any changes are to be made.
Thank you! @G1Joshi
> Adding C++ Code for Preorder Tree Traversal (Issue #20)

- Binary Tree/sukritishah15_postorderTraversal.cpp
Adding C++ Code for Postorder Tree Traversal (Issue #21)
Please let me know if any changes are required.
Thank you! @G1Joshi
> Adding C++ Code for Postorder Tree Traversal (Issue #21)

- Array/MeeeCoder_ArraySum.cpp
add MeeeCoder_ArraySum.cpp in Array of Data-Structues
> add MeeeCoder_ArraySum.cpp

- Linked List/KshitijDarekar_LinkedListPalindrome.c
A menu driven program to check whether a linked list is palindrome or not using Stack in C.
Following Operations are performed :
a. Push an element .
b. Pop an element .
c. check List is palindrome.
d. Display the status .
> Add KshitijDarekar_LinkedListPalindrome.c

- Binary Tree/postorder(Mohitbalwani26).py
Reference issue #21
Added Postorder traversal of binary tree in python.
> added postorder traversal in python

- Stack/post_to_pre.py
Conversion from postfix to prefix
> Postfix To Prefix Conversion

- Graph/m-e-r-l-i-n_bfs_iterative.java
- Graph/m-e-r-l-i-n_dfs_iterative.java
- Graph/m-e-r-l-i-n_dfs_recursive.java
Added some codes related to basic graph algorithms. 
Please check.
> graph algorithms

- Binary Tree/search_an_element_in_binary search_tree.java
I have added the solution to the search an element in the binary search tree question.
This is my first contribution.
> solved the search element in bst question

- Linked List/kavyasritulabandu_inserting_in_sortedlinkedlist.py
As a part of this PR, I am adding python function to insert an element into a sorted linked list.
> Added Script to insert an element in sorted linkedlist

- Queue/queueUsingStack.cpp
Created a program using C++ which uses two stacks to implement a queue it also contains the main function which shows a demo of how the code works.
> added queue using stack resolves #17

- String/TunrayoIlawole_Palindrome.js
Javascript palindrome string checker
> add palindrome string checker

- Binary Tree/adiksha20_sumofnodes.cpp
- Queue/QueueUsingStacks.java
Added Queue Using Stacks File and implemented the program in java
> Added QueueUsingStack

- Stack/Stack Operation.c
One code added which illustrates the stack operation in C.
> Stack Operation

- Array/searchIndex-alessia.js
Add solution for search index problem in array
> Add solution for search index problem

- Binary Search Tree/sgavil_SearchBST.cpp
Added c++ code for issue #22 . Search for BST
> Added search for BST in C++ 

- Linked List/STACLINK.C
This is like a hybrid approach in which a stack is implemented using a linkedlist i.e. a nonlinear data structure.
> Stack Using a LinkedList

- B+Tree/BPLUSTREE.C
B+ tree data structure used in DBMS implemented successfully
> B+ Tree Datat Structure Implemented

- SegmentTree/Segmenttreermq.java
Added Segment Tree Implementation Range Minimum Query along with update index option
> Added Segment Tree Implementation Range Minimum Query

- Array/devmohit-live_SumOfArray.py
- Binary Tree/devmohit_SumOfNode.java
- Linked List/devmohit_KthNode.java
Added a Java program that prints the Kth Node from the end of Linked List
> Added Kth Node from the end of Linked List in Java | Mohit

- Array/Circularqueue.py
- C/Prefixtoinfix.c
- Priorityqueue.py
This is an Successful Program that converts the Prefix into infix with no bugs in it  which is successfully compiled and run on Windows System to produce desired output.
> Added Prefixtoinfix.c

- AVL Tree/AVLTREE.C
AVL Tree Creation, Insertion and Deletion along with proper Rotations successfully implemented
> AVL Tree Data structure implemented

- B-Tree/BTREE.C
B- Tree DS implemented successfully
> B-Tree Data structure implemented

- Linked List/Stack-Implementation Using Linked List.c
adding stack implementation using linked list.
> Create Stack-Implementation Using Linked List.c

- Linked List/remove-duplicate_alessia.js
Add solution for remove duplicate from a list
> Add solution for remove duplicate from a list

- Array/removeDuplicate-ale.js
Add solution for remove duplicate
> Add my solution for remove duplicate

- String/Palindrome(krishita30j).py
Added Palindrome string solution under String section.
> Adding Palindrome program

- String/Horspools_string_match.c
> Add the new file

- Array/Spiralarray.cpp
- Matrix/Spiralmatrix.cpp
- Matrix/spiralmatrix2.cpp
programm to traverse 2d aarray matrix in spiral way
> spiral matrix

- Array/sumOfArray(krishita30j).py
- Binary Tree/heightOfBT(krishita30j).py
- Binary Tree/maxBT(krishita30j).py
- Binary Tree/sumOfNodesBT(krishita30j).py
Issue #27 
Added Maximum in BT solution under Binary tree section.
> Max in BT.

- Array/sumOfArray(krishita30j).py
- Binary Tree/heightOfBT(krishita30j).py
- Binary Tree/sumOfNodesBT(krishita30j).py
Issue #29 
Adding program to find sum of nodes in BT.
> Sum of nodes in BT.

- Array/sumOfArray(krishita30j).py
- Binary Tree/heightOfBT(krishita30j).py
Issue #26 
Program to find the height of binary tree(Python).
> Height of binary tree.

- Array/sumOfArray(krishita30j).py
Issue #112 
Added Sum of elements of an array solution under Array section.
> Adding Sum of elements of an array program(Python).

- Stack/sumeetweb_StackUsingLinkedList.c
Implemented Stack Using Linked List in C
> Implemented Stack Using Linked List in C

- Linked List/passionlord_single-linked-list-palindrome.c
added single linkedlist is palindrome or not in c
> single linked list is palindrome  or not

- Binary Tree/cBridges851_sum-of-nodes.cs
A program has been created in C# that calculates the sum of all the nodes in the binary tree.
The program works by:
- The user first of all inputting the number of nodes that will be in the tree
- The data for each node is received
- The binary tree is made
- Each node of the tree is accessed as part of level-order traversal and is added to a queue
- The current node's data is added to a sum variable
- The current node's left and right nodes are added to the queue
- This process repeats until the queue is empty
> Calculate Sum of Nodes in BT in C#

- Linked List/double_linked_list.py
Implementation of a double linked in python, with exception.
> Double linked list implementation in python

- Binary Tree/sagar-monga_DepthFirstSearch.c
Please label as hacktoberfest-accepted upon merging. Thank you :)
> Added DFS in C

- Binary Tree/Mohitbalwani26_preorder_traversal.py
Reference #20 
added preorder_traversal of binary tree in python.
> added preorder_traversal

- Binary Tree/Mohitbalwani26_inorder_traversal.py
Reference #19 
added inorder_traversal for binary tree in python.
> added inorder_traversal

- Linked List/detect_loop.cpp
I added cpp code to detect loop in a linked list using Floyd's cycle finding algorithm.
> Added cpp code to detect loop in linked list

- Linked List/rishika-singh_middle elemet of linked list.md
> Middle of the linked list

- Binary Search Tree/jhalak27_breadthFirstSearch.cpp
For issue #23 
Added Breadth-first search for directed graph
> Added Breadth First Search in c++

- Array/PramodRaoB_largestNoInArray.c
Add program that finds the largest number in a given array of given length.
> Add program to find largest number in array

- Array/rotateArray.cpp
> Added program to rotate an array

- Array/subsetOfGivenSum.cpp
> Count number of subsets with given sum

- Others/sieveOfEratosthenes.cpp
> Segmented Sieve of Eratosthenese for prime numbers

- Binary Search Tree/Java/Lisaverma_bstimplementation/Main.java
- Binary Search Tree/Java/Lisaverma_bstimplementation/Tree.java
- Binary Search Tree/Java/Lisaverma_bstimplementation/TreeNode.java
add binary search tree implementation
> add bst implementation

- Array/C/Bubble.c
Fixed issue#256
Bubble sort using C.
> fixed issue#256 [ Bubble sort problem using C ]

- Python/Gmatieso/classes .py
This python class  has  color and flavor defined in it . which are accessed by creating an instance  of Apple class then accessing the 
attributes using the dot notation
> Apple Class

- Binary Tree/C/HANS-2002_dfs-in-trees.c
> Implemented dfs for trees

- Binary Tree/C/HANS-2002_bfs-in-trees.c
- Binary Tree/C/HANS-2002_dfs-in-trees.c
> Implemented bfs on trees

- Binary Tree/Java/adityarajbhagat2002_inorder.java
> Added inorder for trees in java

- Binary Search Tree/C/Ishan77_BST.c
- Sorting/shell_sort.c
shell sort implementation in c
> shell sort

- Queue/JavaScript/circular-queue.js
Circular Queue Implementation in JavaScript.
> Added circular queue implementation in javascript

- Linked List/C/HANS-2002_find_an_element_in_linked_list.c
> Added program in C to search an element in linked list

- Linked List/Python/Kth-node-from-end-linkedlist.py
This algo uses a single iteration using a two pointer approach
> Kth Node from the end of Linked List

- Linked List/C/thecoderash_Insertion_in_Sorted_Linked_List.c
> Contributed to Issue#11

- Linked List/C/thecoderash_Reverse_a_Linked_List.c
Contributed to Issue #6  Please look forward to merge it.
> Worked on Issue #6

- Linked List/C/thecoderash_Palindrome_Linked_List.c
Contributed to fixing Issue #9
> Worked on Issue #9

- Binary Tree/C/thecoderash_Height_of_the_Binary_Tree.c
> worked on Issue #26

- Binary Search Tree/C/thecoderash_Search_in_Binary_Search_Tree.c
> worked on Issue#22

- Linked List/C++/Rohan-2107_Search_in_Linked_List.cpp
> Create cpp program for searching in linked list
